export const PICX_REPO_NAME = 'XPoet/arzhp'
export const INIT_REPO_NAME = 'arzhp-images-hosting'
export const INIT_REPO_DESC = 'arzhp images hosting repository'
export const INIT_REPO_BARNCH = 'master'
export const GH_PAGES = 'gh-pages'
export const PICX_UPLOAD_IMG_DESC = 'ARZHP(https://img.arzhp.cn)'
export const PICX_UPLOAD_IMGS_DESC = 'ARZHP(https://img.arzhp.cn)'
export const PICX_DEL_IMG_DESC = 'ARZHP(https://img.arzhp.cn)'
